### ISSUE TITLE
OSMCha mixes changes of multiple changesets in one

### ISSUE THREAD

**Issue by tordans** [OSMCha/osmcha-frontend#492]
I'm submitting a bug report

This is wrong:
- Open https://osmcha.org/changesets/93550765/
- Look at the node in the middle 1455122211
  => OSMCha shows two changes in this changeset for this node (crossing:island + tactile_paving)

![image](https://user-images.githubusercontent.com/111561/98528736-02503780-227d-11eb-9a26-d7be1ebdf31b.png)

However:
https://www.openstreetmap.org/node/1455122211/history
The history shows, that those changes are done in two separate changesets.

1. #93550765 => adds the crossing:island
  https://www.openstreetmap.org/changeset/93550765
  https://osmcha.org/changesets/93550765?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22dAnjou%22%2C%22value%22%3A%22dAnjou%22%7D%5D%7D
2. #93550776 => adds the tactile_paving
  https://www.openstreetmap.org/changeset/93550776
  https://osmcha.org/changesets/93550776?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22dAnjou%22%2C%22value%22%3A%22dAnjou%22%7D%5D%7D

**Comment by willemarcel** [comment]
@tordans We've implemented some changes on how we generate the map visualization today. Let me know if you find some other similar case.

Related to https://github.com/osmlab/changeset-map/issues/102

**Comment by matkoniecz** [comment]
The same happens with https://osmcha.org/changesets/94100583/ (compare https://www.openstreetmap.org/changeset/94100583 )

It clearly causes significant confusion - see https://github.com/westnordost/StreetComplete/issues/2272 and https://github.com/westnordost/StreetComplete/issues/2253

![screen](https://user-images.githubusercontent.com/899988/99158956-86207e80-26d8-11eb-98ed-af98059c6c56.png)

**Comment by tordans** [comment]
It is still happening at https://osmcha.org/changesets/94151729?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22dAnjou%22%2C%22value%22%3A%22dAnjou%22%7D%5D%7D 

From quickly reading over https://github.com/osmlab/changeset-map/issues/102, it might be needed to explain in the UI, what is going on.

**Comment by andrewharvey** [comment]
wonder if this is the same root cause as #467

**Comment by fnordiff** [comment]
I just noticed that OSMCha seems to have the colored numbers in the details overlay correct in these cases. You can see that in the screenshot above (changeset 94100583) https://github.com/mapbox/osmcha-frontend/issues/492#issuecomment-727279756

It says "4" in yellow and zero in green/red, which corresponds to the four ways listed in https://www.openstreetmap.org/changeset/94100583 .  I've noticed this behavior in other changesets as well.

So the data in the detail "overlay" in front of the map and the "changeset list" on the left seem to be correct, just not the representation on the map, which also highlights things that have not changed in this changeset.

**Comment by mxxcon** [comment]
This problem is still going on. It's especially problematic with changesets coming from StreetComplete.

**Comment by rurseekatze** [comment]
The bug seems to still exist, see https://github.com/OSMCha/osmx-adiff-builder/issues/2 for further details.
